# 书籍缺失文章检查报告 (缺失数量: 1-20)

生成时间: 2025年12月26日

找到 2 本书籍缺失数量在 1-20 之间

## 汇总统计

| 书籍名称 | 总数 | 已有 | 缺失 | 完成率 |
|---------|------|------|------|--------|
| algorithm/dynamic-programming | 119 | 115 | 4 | 96.6% |
| algorithm/graph-algorithms | 95 | 89 | 6 | 93.7% |

---

## [1] algorithm/dynamic-programming

- **TOC 路径**: `E:\CoderBooks\src\books\algorithm\dynamic-programming\book_zh\toc.md`
- **总文章数**: 119
- **已存在**: 115
- **缺失数量**: 4

### 缺失文章列表

#### 章节: 第九部分：状态压缩 DP

缺失文章数: 1

1. **实战：火柴拼正方形**
   - 路径: `state-compression/practice-matchsticks-to-square.md`
   - 完整路径: `E:\CoderBooks\src\books\algorithm\dynamic-programming\book_zh\state-compression\practice-matchsticks-to-square.md`

#### 章节: 第十部分：数位 DP

缺失文章数: 1

1. **实战：统计特殊数字**
   - 路径: `digit-dp/practice-count-special-numbers.md`
   - 完整路径: `E:\CoderBooks\src\books\algorithm\dynamic-programming\book_zh\digit-dp\practice-count-special-numbers.md`

#### 章节: 第十二部分：DP 优化技巧

缺失文章数: 2

1. **实战：单调队列优化示例**
   - 路径: `dp-optimization/practice-monotonic-queue-dp.md`
   - 完整路径: `E:\CoderBooks\src\books\algorithm\dynamic-programming\book_zh\dp-optimization\practice-monotonic-queue-dp.md`

2. **实战：斜率优化示例**
   - 路径: `dp-optimization/practice-convex-hull-trick.md`
   - 完整路径: `E:\CoderBooks\src\books\algorithm\dynamic-programming\book_zh\dp-optimization\practice-convex-hull-trick.md`

---

## [2] algorithm/graph-algorithms

- **TOC 路径**: `E:\CoderBooks\src\books\algorithm\graph-algorithms\book_zh\toc.md`
- **总文章数**: 95
- **已存在**: 89
- **缺失数量**: 6

### 缺失文章列表

#### 章节: 第四部分：图的遍历综合

缺失文章数: 3

1. **实战：课程表 II**
   - 路径: `graph-traversal/practice-course-schedule-ii.md`
   - 完整路径: `E:\CoderBooks\src\books\algorithm\graph-algorithms\book_zh\graph-traversal\practice-course-schedule-ii.md`

2. **实战：判断二分图**
   - 路径: `graph-traversal/practice-is-bipartite.md`
   - 完整路径: `E:\CoderBooks\src\books\algorithm\graph-algorithms\book_zh\graph-traversal\practice-is-bipartite.md`

3. **实战：可能的二分法**
   - 路径: `graph-traversal/practice-possible-bipartition.md`
   - 完整路径: `E:\CoderBooks\src\books\algorithm\graph-algorithms\book_zh\graph-traversal\practice-possible-bipartition.md`

#### 章节: 第九部分：高级搜索技巧

缺失文章数: 1

1. **实战：推箱子**
   - 路径: `search-advanced/practice-minimum-moves-to-move-a-box.md`
   - 完整路径: `E:\CoderBooks\src\books\algorithm\graph-algorithms\book_zh\search-advanced\practice-minimum-moves-to-move-a-box.md`

#### 章节: 第十部分：二分图与匹配

缺失文章数: 2

1. **实战：判断二分图**
   - 路径: `bipartite/practice-is-bipartite.md`
   - 完整路径: `E:\CoderBooks\src\books\algorithm\graph-algorithms\book_zh\bipartite\practice-is-bipartite.md`

2. **实战：二分图最大匹配应用**
   - 路径: `bipartite/practice-max-bipartite-matching.md`
   - 完整路径: `E:\CoderBooks\src\books\algorithm\graph-algorithms\book_zh\bipartite\practice-max-bipartite-matching.md`

---

